### ISSUE TITLE
Desktop Extension UX/UI enhancements

### ISSUE THREAD

**Issue by jhmarina** [epinio/extension-docker-desktop#56]
## What are we doing

- This Epic is a follow-up of [this issue](https://github.com/epinio/extension-docker-desktop/issues/43). 
- It focuses on implementing enhancements to the overall UI and UX, ensuring it provides valuable information and metrics to users. 
- After refreshing the UI, the team will gradually implement new features and improvements, which will be defined in the future
- Rancher Desktop builds upon the current extension implementation, with some adjustments, benefiting from these improvements.

## Why are we doing it

- Many users have installed the Docker Desktop extension, which promotes the project and generates interest in Epinio among developers. A properly functioning extension enhances the overall appeal of Epinio.
- [These metrics](https://github.com/epinio/epinio/files/12792952/Epinio_Dashboard_2023-10-02T0807.pdf) show a high level of engagement.
- Since the Rancher Desktop extension utilizes the Docker Desktop extension as its base, its users will also benefit from all the improvements applied to the Docker Desktop extension.

## References

- [Epinio Docker Desktop UI Mockup](https://www.figma.com/file/ZMDes98PtKYEHQiMKevCGT/Epinio-Docker-v2?type=design&node-id=0%3A1&mode=design&t=wWp7QNN9d032hSsl-1)

![Image](https://github.com/epinio/epinio/assets/2351510/c3717995-0893-4ccb-bc31-1d831512b36a)
![Image](https://github.com/epinio/epinio/assets/2351510/6c43da8a-d2e5-4cae-9115-6d2ce558b45f)

```[tasklist]
### Tasks
- [ ] https://github.com/epinio/extension-docker-desktop/issues/55
- [ ] https://github.com/epinio/extension-docker-desktop/issues/54
- [ ] https://github.com/epinio/extension-docker-desktop/issues/53
- [ ] https://github.com/epinio/epinio/issues/2665
- [ ] https://github.com/epinio/epinio/issues/2667
- [ ] https://github.com/epinio/epinio/issues/2668
- [ ] Login modal UI
- [ ] https://github.com/epinio/epinio/issues/2664
- [ ] https://github.com/epinio/epinio/issues/2666
- [ ] https://github.com/epinio/epinio/issues/2671
- [ ] https://github.com/epinio/epinio/issues/2669
- [ ] https://github.com/epinio/epinio/issues/2670
```
