### ISSUE TITLE
Create the application detail view.

### ISSUE THREAD

**Issue by jhmarina** [epinio/extension-docker-desktop#58]
Implement the app detail view page. This is an entirely new section and is potentially an Epic. It mimics the Epinio UI in terms of the information that is delivered.

**Mockup**

![app-detail-updated](https://github.com/epinio/epinio/assets/2351510/494eba2b-4c18-4969-81fa-22a3247c887e)

```[tasklist]
### Subtasks
- [ ] Implement the routes overview widget
- [ ] Implement the deployment overview widget
- [ ] Implement the Instances widget
- [ ] Implement information widgets (Memory & CPU)
```
